-- =====================================================
-- Script d'insertion des données ENI (généré depuis le livret PDF)
-- Ordre : groups -> teachers -> subjects -> teacher_subjects
-- Matricule : ENIxxx | Email généré à partir du prénom
-- =====================================================

-- ---------- GROUPS ----------
INSERT INTO groups (id, code, name, level) VALUES (1, 'TC-L1', 'Tronc Commun', 'L1');
INSERT INTO groups (id, code, name, level) VALUES (2, 'IG-L2', 'Informatique Générale', 'L2');
INSERT INTO groups (id, code, name, level) VALUES (3, 'IG-L3', 'Informatique Générale', 'L3');
INSERT INTO groups (id, code, name, level) VALUES (4, 'IG-M1', 'Informatique Générale', 'M1');
INSERT INTO groups (id, code, name, level) VALUES (5, 'IG-M2', 'Informatique Générale', 'M2');
INSERT INTO groups (id, code, name, level) VALUES (6, 'GB-L2', 'Génie Logiciel et Base de Données', 'L2');
INSERT INTO groups (id, code, name, level) VALUES (7, 'GB-L3', 'Génie Logiciel et Base de Données', 'L3');
INSERT INTO groups (id, code, name, level) VALUES (8, 'GB-M1', 'Génie Logiciel et Base de Données', 'M1');
INSERT INTO groups (id, code, name, level) VALUES (9, 'GB-M2', 'Génie Logiciel et Base de Données', 'M2');
INSERT INTO groups (id, code, name, level) VALUES (10, 'ASR-L2', 'Administration des Systèmes Réseaux', 'L2');
INSERT INTO groups (id, code, name, level) VALUES (11, 'ASR-L3', 'Administration des Systèmes Réseaux', 'L3');
INSERT INTO groups (id, code, name, level) VALUES (12, 'ASR-M1', 'Administration des Systèmes Réseaux', 'M1');
INSERT INTO groups (id, code, name, level) VALUES (13, 'ASR-M2', 'Administration des Systèmes Réseaux', 'M2');
INSERT INTO groups (id, code, name, level) VALUES (14, 'GID-M1', 'Gouvernance et Ingénierie de Données', 'M1');
INSERT INTO groups (id, code, name, level) VALUES (15, 'GID-M2', 'Gouvernance et Ingénierie de Données', 'M2');
INSERT INTO groups (id, code, name, level) VALUES (16, 'OCC-M1', 'Objets Connectés et Cybersécurités', 'M1');
INSERT INTO groups (id, code, name, level) VALUES (17, 'OCC-M2', 'Objets Connectés et Cybersécurités', 'M2');

-- ---------- TEACHERS ----------
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (1, 'ENI001', 'Nivonirina Yvette Louisa', 'Andriamora Rabetoandro', 'nivonirinayvettelouisa@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (2, 'ENI002', 'Bertin', 'Andry', 'bertin@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (3, 'ENI003', 'William Germain', 'Dimbisoa', 'williamgermain@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (4, 'ENI004', 'Mihajasoa Léa', 'Fanomezana', 'mihajasoalea@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (5, 'ENI005', 'Gesazafy', 'Gilante', 'gesazafy@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (6, 'ENI006', 'Aimé Richard', 'Hajalalaina', 'aimerichard@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (7, 'ENI007', 'Robert', 'Lira', 'robert@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (8, 'ENI008', 'Thomas', 'Mahatody', 'thomas@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (9, 'ENI009', '-', 'Marius', 'enseignant9@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (10, 'ENI010', 'Auguste Patrice', 'Rabemanantsoa', 'augustepatrice@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (11, 'ENI011', 'Louis Haja', 'Rabetafika', 'louishaja@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (12, 'ENI012', 'Fontaine', 'Rafamantanantsoa', 'fontaine@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (13, 'ENI013', 'Jean Roger', 'Rafanomezantsoa', 'jeanroger@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (14, 'ENI014', 'Angelo', 'Raherinirina', 'angelo@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (15, 'ENI015', 'Antsa Cyprienne', 'Rakotoasimbahoaka', 'antsacyprienne@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (16, 'ENI016', 'Cyprien Robert', 'Rakotoasimbahoaka', 'cyprienrobert@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (17, 'ENI017', 'Hasina', 'Rakotonirainy', 'hasina@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (18, 'ENI018', 'Janvier Benjamin', 'Rakotonirina', 'janvierbenjamin@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (19, 'ENI019', 'Jean Christian', 'Ralaivao', 'jeanchristian@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (20, 'ENI020', 'Bénédicte', 'Ralamboarisoa', 'benedicte@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (21, 'ENI021', 'Andriantiana Bertin Olivier', 'Ramamonjisoa', 'andriantianabertinolivier@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (22, 'ENI022', 'Germain Lalao', 'Randrianandraina', 'germainlalao@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (23, 'ENI023', 'Lala Ferdinand', 'Randrianomenjanahary', 'lalaferdinand@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (24, 'ENI024', 'Madison', 'Rasoloarijaona', 'madison@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (25, 'ENI025', 'Volatiana Marielle', 'Ratianantitra', 'volatianamarielle@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (26, 'ENI026', 'Venot', 'Ratiarson', 'venot@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (27, 'ENI027', 'Alain Josué', 'Ratovondrahona', 'alainjosue@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (28, 'ENI028', 'Hajarisena', 'Razafimahatratra', 'hajarisena@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (29, 'ENI029', 'Victor', 'Razafimampiandra', 'victor@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (30, 'ENI030', 'Clément Aubert', 'Razafindramonja', 'clementaubert@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (31, 'ENI031', 'Dieudonné Michel', 'Razafindrandriatsimaniry', 'dieudonnemichel@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (32, 'ENI032', 'Toky Arisetra', 'Razafinimaro', 'tokyarisetra@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (33, 'ENI033', 'Martial', 'Razakatiana', 'martial@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (34, 'ENI034', 'Hantarisoa Solondraibe', 'Razanamahefa', 'hantarisoasolondraibe@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (35, 'ENI035', 'Alain Nimbol', 'Rivosoaniaina', 'alainnimbol@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (36, 'ENI036', '-', 'Siaka', 'enseignant36@gmail.com', NULL, NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, matricule, first_name, last_name, email, phone, grade, specialty, photo, department_id) VALUES (37, 'ENI037', 'Brice Evrard', 'Tarehy', 'briceevrard@gmail.com', NULL, NULL, NULL, NULL, NULL);

-- ---------- SUBJECTS ----------
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (1, 'TC-L1-001', 'Base d''algèbre 1', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (2, 'TC-L1-002', 'Base d''analyse 1', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (3, 'TC-L1-003', 'Probabilité et Statistique', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (4, 'TC-L1-004', 'Mathématiques discrètes', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (5, 'TC-L1-005', 'Algorithme et structure de données en C', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (6, 'TC-L1-006', 'Initiation à la POO', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (7, 'TC-L1-007', 'Langage C', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (8, 'TC-L1-008', 'Développement de site web en HTML/CSS', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (9, 'TC-L1-009', 'Technologie XML et DHTML', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (10, 'TC-L1-010', 'Système d''exploitation Unix', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (11, 'TC-L1-011', 'Système d''exploitation Windows', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (12, 'TC-L1-012', 'Théorie des réseaux', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (13, 'TC-L1-013', 'Architecture des ordinateurs', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (14, 'TC-L1-014', 'Technologies des réseaux', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (15, 'TC-L1-015', 'Electronique analogique', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (16, 'TC-L1-016', 'Electronique numérique', 3, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (17, 'TC-L1-017', 'Introduction aux systèmes embarqués', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (18, 'TC-L1-018', 'Base de l''Informatique', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (19, 'TC-L1-019', 'Comptabilité générale', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (20, 'TC-L1-020', 'Anglais 1', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (21, 'TC-L1-021', 'Français 1', 2, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (22, 'TC-L1-022', 'Projet système et Base de données', 1, 1);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (23, 'IG-L2-023', 'Analyse 2', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (24, 'IG-L2-024', 'Algèbre 2', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (25, 'IG-L2-025', 'Probabilité et Statistique 2', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (26, 'IG-L2-026', 'Langage Python', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (27, 'IG-L2-027', 'Programmation objet en C++', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (28, 'IG-L2-028', 'Algorithme et structure de données avancés en C', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (29, 'IG-L2-029', 'Base de données relationnelles', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (30, 'IG-L2-030', 'MERISE 1', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (31, 'IG-L2-031', 'Développement d''applications SPA', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (32, 'IG-L2-032', 'Développement d''applications en C#', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (33, 'IG-L2-033', 'Développement web en PHP', 4, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (34, 'IG-L2-034', 'Services réseaux', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (35, 'IG-L2-035', 'Base de l''administration des réseaux', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (36, 'IG-L2-036', 'Communication et Routage IP', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (37, 'IG-L2-037', 'Maintenance des systèmes d''exploitation', 3, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (38, 'IG-L2-038', 'Administration système Unix', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (39, 'IG-L2-039', 'Administration système Microsoft', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (40, 'IG-L2-040', 'Langage Assembleur', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (41, 'IG-L2-041', 'Electronique analogique 2', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (42, 'IG-L2-042', 'Programmation des microcontrôleurs', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (43, 'IG-L2-043', 'Anglais 2', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (44, 'IG-L2-044', 'Technique de communication', 2, 2);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (45, 'IG-L3-045', 'Langage JAVA 1', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (46, 'IG-L3-046', 'Langage JAVA 2', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (47, 'IG-L3-047', 'Langage Python', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (48, 'IG-L3-048', 'Technologies JSP et Servlet 1', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (49, 'IG-L3-049', 'Développement Mobile', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (50, 'IG-L3-050', 'Génie Logiciel', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (51, 'IG-L3-051', 'Administration de Base de données', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (52, 'IG-L3-052', 'UML', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (53, 'IG-L3-053', 'MERISE 2', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (54, 'IG-L3-054', 'Patrons GRASP', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (55, 'IG-L3-055', 'Téléphonie sur IP', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (56, 'IG-L3-056', 'Réseaux mobiles', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (57, 'IG-L3-057', 'Administration réseaux Unix 1', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (58, 'IG-L3-058', 'Administration réseaux Microsoft 1', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (59, 'IG-L3-059', 'Assembleur appliqué', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (60, 'IG-L3-060', 'Interopérabilité et architecture client/serveur', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (61, 'IG-L3-061', 'Réseaux IP/MPLS', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (62, 'IG-L3-062', 'Base de la cybersécurité', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (63, 'IG-L3-063', 'Architecture réseaux sécurisées', 3, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (64, 'IG-L3-064', 'Anglais', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (65, 'IG-L3-065', 'Technique de communication', 2, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (66, 'IG-L3-066', 'Marketing', 1, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (67, 'IG-L3-067', 'Organisation et Management', 1, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (68, 'IG-L3-068', 'Entreprenariat', 1, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (69, 'IG-L3-069', 'Gestion de Projet', 1, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (70, 'IG-L3-070', 'Droit des affaires et du travail', 1, 3);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (71, 'IG-M1-071', 'Recherche opérationnelle', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (72, 'IG-M1-072', 'Analyse des données', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (73, 'IG-M1-073', 'Analyse numérique', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (74, 'IG-M1-074', 'Algorithmique avancé', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (75, 'IG-M1-075', 'Technologie avancée en Java', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (76, 'IG-M1-076', 'Technologie web avancée', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (77, 'IG-M1-077', 'Technologie Nodejs', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (78, 'IG-M1-078', 'Intégration Web-SIG', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (79, 'IG-M1-079', 'Ingénierie des besoins', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (80, 'IG-M1-080', 'Génie logiciel', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (81, 'IG-M1-081', 'Interface Homme-Machine', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (82, 'IG-M1-082', 'Intelligence artificielle', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (83, 'IG-M1-083', 'Machine Learning et Deep Learning', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (84, 'IG-M1-084', 'Programmation parallèle et distribuée', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (85, 'IG-M1-085', 'Programmation des réseaux', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (86, 'IG-M1-086', 'Systèmes embarqués et temps réels', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (87, 'IG-M1-087', 'Réseau de Pétri et programmation multitâche', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (88, 'IG-M1-088', 'Sécurité sous Unix', 2, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (89, 'IG-M1-089', 'Administration système et réseau avancée', 3, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (90, 'IG-M1-090', 'Technique de communication', 1.5, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (91, 'IG-M1-091', 'Anglais techniques', 1.5, 4);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (92, 'IG-M2-092', 'Réutilisation logiciel & frameworks', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (93, 'IG-M2-093', 'Architecture Orienté Service', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (94, 'IG-M2-094', 'Développement d''applications mobiles', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (95, 'IG-M2-095', 'Administration avancée de base de données', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (96, 'IG-M2-096', 'Méthodes Agile', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (97, 'IG-M2-097', 'Interaction Homme-Machine 2', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (98, 'IG-M2-098', 'Système d''Information décisionnelle', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (99, 'IG-M2-099', 'Aide à la décision et optimisation multicritère', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (100, 'IG-M2-100', 'Technologie de virtualisation et SDN', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (101, 'IG-M2-101', 'Sensibilisation à l''Internet des Objets', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (102, 'IG-M2-102', 'GRID et CLUSTER', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (103, 'IG-M2-103', 'Sécurité avancée', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (104, 'IG-M2-104', 'MPLS et QoS', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (105, 'IG-M2-105', 'Téléphonie sur IP avancée', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (106, 'IG-M2-106', 'Réseau mobile avancée', 2, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (107, 'IG-M2-107', 'Modélisation mathématique', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (108, 'IG-M2-108', 'Système multi-agents', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (109, 'IG-M2-109', 'Python pour Machine Learning', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (110, 'IG-M2-110', 'Système expert', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (111, 'IG-M2-111', 'Méthodologie d''élaboration de mémoires', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (112, 'IG-M2-112', 'Méthodologie de recherche', 3, 5);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (113, 'GB-L2-113', 'Base d''algèbre 2', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (114, 'GB-L2-114', 'Base d''analyse 2', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (115, 'GB-L2-115', 'Probabilité et Statistique', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (116, 'GB-L2-116', 'Programmation linéaire', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (117, 'GB-L2-117', 'Algorithmique et structure de données avancés', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (118, 'GB-L2-118', 'Programmation Orienté Objet en C++', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (119, 'GB-L2-119', 'Langage Java', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (120, 'GB-L2-120', 'Langage Python', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (121, 'GB-L2-121', 'Technologie PHP', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (122, 'GB-L2-122', 'Base de données relationnelles', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (123, 'GB-L2-123', 'Base de données avancées', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (124, 'GB-L2-124', 'SGBD MySQL et PostGreSQL', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (125, 'GB-L2-125', 'Introduction aux méthodes', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (126, 'GB-L2-126', 'MERISE 1', 3, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (127, 'GB-L2-127', 'MERISE 2', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (128, 'GB-L2-128', 'Développement d''application SPA', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (129, 'GB-L2-129', 'Développement d''application en C#', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (130, 'GB-L2-130', 'Comptabilité analytique', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (131, 'GB-L2-131', 'Méthode de Travail Universitaire', 1, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (132, 'GB-L2-132', 'Anglais', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (133, 'GB-L2-133', 'Technique de communication', 2, 6);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (134, 'GB-L3-134', 'Langage JAVA', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (135, 'GB-L3-135', 'Technologie JAVA', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (136, 'GB-L3-136', 'Technologie Python', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (137, 'GB-L3-137', 'Technologies JSP et Servlet 1', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (138, 'GB-L3-138', 'Administration de Base de données', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (139, 'GB-L3-139', 'UML', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (140, 'GB-L3-140', 'Patrons de conception', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (141, 'GB-L3-141', 'Patrons GRASP et GoF', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (142, 'GB-L3-142', 'Génie Logiciel 1', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (143, 'GB-L3-143', 'Développement Web API', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (144, 'GB-L3-144', 'Développement mobile', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (145, 'GB-L3-145', 'Technologie web mobile', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (146, 'GB-L3-146', 'Interaction Homme-Machine', 3, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (147, 'GB-L3-147', 'Anglais', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (148, 'GB-L3-148', 'Technique de communication', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (149, 'GB-L3-149', 'Marketing', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (150, 'GB-L3-150', 'Organisation et Management', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (151, 'GB-L3-151', 'Entreupeunariat', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (152, 'GB-L3-152', 'Gestion de Projet', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (153, 'GB-L3-153', 'Droit des affaires et du travail', 2, 7);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (154, 'GB-M1-154', 'Recherche opérationnelle', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (155, 'GB-M1-155', 'Analyse des données', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (156, 'GB-M1-156', 'Analyse numérique', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (157, 'GB-M1-157', 'Réseau de Pétri et programmation multi-tâche', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (158, 'GB-M1-158', 'Algorithmique avancé', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (159, 'GB-M1-159', 'Technologie avancée en Java', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (160, 'GB-M1-160', 'Technologie web avancée', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (161, 'GB-M1-161', 'Développement d''application Mobile 2', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (162, 'GB-M1-162', 'Intégration Web-SIG', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (163, 'GB-M1-163', 'Ingénierie des besoins', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (164, 'GB-M1-164', 'Génie logiciel avancé', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (165, 'GB-M1-165', 'Interaction Homme-Machine', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (166, 'GB-M1-166', 'Intelligence artificielle', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (167, 'GB-M1-167', 'Machine learning', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (168, 'GB-M1-168', 'Technologie Python', 4, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (169, 'GB-M1-169', 'Technique de communication', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (170, 'GB-M1-170', 'Anglais techniques', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (171, 'GB-M1-171', 'Gestion financière et budgétaire', 3, 8);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (172, 'GB-M2-172', 'Réutilisation logiciel & frameworks', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (173, 'GB-M2-173', 'Architecture Orienté Service', 4, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (174, 'GB-M2-174', 'BPM & Workflow', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (175, 'GB-M2-175', 'Administration avancée de base de données', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (176, 'GB-M2-176', 'DevOps', 4, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (177, 'GB-M2-177', 'Architecture logicielle', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (178, 'GB-M2-178', 'Ingéniérie Dirigée par le Modèle', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (179, 'GB-M2-179', 'Urbanisation des Systèmes d''Information', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (180, 'GB-M2-180', 'Sciences des données', 4, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (181, 'GB-M2-181', 'Méthodes Agile', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (182, 'GB-M2-182', 'Système d''Information décisionnelle', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (183, 'GB-M2-183', 'Aide à la décision et optimisation multi-critère', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (184, 'GB-M2-184', 'Modélisation mathématique', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (185, 'GB-M2-185', 'Système Multi-Agents', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (186, 'GB-M2-186', 'Méthodologie d''élaboration de mémoires', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (187, 'GB-M2-187', 'Méthodologie de recherche', 3, 9);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (188, 'ASR-L2-188', 'Base d''algèbre 2', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (189, 'ASR-L2-189', 'Base d''analyse 2', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (190, 'ASR-L2-190', 'Probabilité et Statistique 2', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (191, 'ASR-L2-191', 'Programmation linéaire', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (192, 'ASR-L2-192', 'Algorithmique et structure de données en C', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (193, 'ASR-L2-193', 'Programmation en C++', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (194, 'ASR-L2-194', 'Langage Python', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (195, 'ASR-L2-195', 'Langage Assembleur', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (196, 'ASR-L2-196', 'Langage JAVA', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (197, 'ASR-L2-197', 'Technologie PHP', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (198, 'ASR-L2-198', 'Technologie javascript', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (199, 'ASR-L2-199', 'Conception des logiciels', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (200, 'ASR-L2-200', 'Base de sécurité des systèmes d''information', 3, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (201, 'ASR-L2-201', 'Administration système Linux', 3, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (202, 'ASR-L2-202', 'Administration système Windows', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (203, 'ASR-L2-203', 'Electronique analogique', 3, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (204, 'ASR-L2-204', 'Programmation des microcontrôleurs', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (205, 'ASR-L2-205', 'Base de l''administration des réseaux', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (206, 'ASR-L2-206', 'Service réseaux', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (207, 'ASR-L2-207', 'Méthodologie de conception des systèmes et réseaux', 3, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (208, 'ASR-L2-208', 'Routage IP', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (209, 'ASR-L2-209', 'Technologie sans fil et fibre optique', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (210, 'ASR-L2-210', 'Sécurité réseaux sous windows', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (211, 'ASR-L2-211', 'Anglais', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (212, 'ASR-L2-212', 'Technique de communication', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (213, 'ASR-L2-213', 'Méthode de Travail Universitaire', 2, 10);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (214, 'ASR-L3-214', 'Technologie JAVA', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (215, 'ASR-L3-215', 'Technologie Python avancé', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (216, 'ASR-L3-216', 'Technologie NodeJs', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (217, 'ASR-L3-217', 'Langage Assembleur appliqué', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (218, 'ASR-L3-218', 'Conception des logiciels', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (219, 'ASR-L3-219', 'Ingeniérie des bases de données', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (220, 'ASR-L3-220', 'Développement d''application mobile', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (221, 'ASR-L3-221', 'Technologie web mobile', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (222, 'ASR-L3-222', 'Introduction au Machine Learning', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (223, 'ASR-L3-223', 'Projet Machine Learning', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (224, 'ASR-L3-224', 'Administration Système Unix 2', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (225, 'ASR-L3-225', 'Administration Système Microsoft 2', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (226, 'ASR-L3-226', 'Cybersécurité', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (227, 'ASR-L3-227', 'Sécurité web, Mail et réseaux sociaux', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (228, 'ASR-L3-228', 'Administration réseaux Unix 1', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (229, 'ASR-L3-229', 'Administration réseaux Microsoft 1', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (230, 'ASR-L3-230', 'Interopérabilité et architecture client/serveur', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (231, 'ASR-L3-231', 'Réseaux IP/MPLS', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (232, 'ASR-L3-232', 'Réseaux d''opérateurs', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (233, 'ASR-L3-233', 'Téléphonie sur IP', 3, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (234, 'ASR-L3-234', 'Anglais', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (235, 'ASR-L3-235', 'Technique de communication', 2, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (236, 'ASR-L3-236', 'Entreupeunariat', 1, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (237, 'ASR-L3-237', 'Gestion de Projet', 1, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (238, 'ASR-L3-238', 'Droit des affaires et du travail', 1, 11);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (239, 'ASR-M1-239', 'Recherche opérationnelle', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (240, 'ASR-M1-240', 'Analyse des données', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (241, 'ASR-M1-241', 'Analyse numérique', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (242, 'ASR-M1-242', 'Réseau de Pétri et programmation multi-tâche', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (243, 'ASR-M1-243', 'Algorithmique avancé', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (244, 'ASR-M1-244', 'Technologie avancée en Java', 2, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (245, 'ASR-M1-245', 'Technologie de virtualisation et conteneurisation', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (246, 'ASR-M1-246', 'Intelligence artificielle', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (247, 'ASR-M1-247', 'Python pour Machine Learning', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (248, 'ASR-M1-248', 'Linux pour le DevOps', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (249, 'ASR-M1-249', 'Programmation des réseaux', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (250, 'ASR-M1-250', 'Administration système avancée', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (251, 'ASR-M1-251', 'Administration réseau en python', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (252, 'ASR-M1-252', 'Systèmes embarqués et temps réels', 4, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (253, 'ASR-M1-253', 'Sécurité sous Unix', 3, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (254, 'ASR-M1-254', 'Technique de communication', 2, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (255, 'ASR-M1-255', 'Anglais techniques', 2, 12);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (256, 'ASR-M2-256', 'GRID et CLUSTER', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (257, 'ASR-M2-257', 'Technologie de virtualisation', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (258, 'ASR-M2-258', 'Internet des Objets', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (259, 'ASR-M2-259', 'MPLS et QoS', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (260, 'ASR-M2-260', 'Réseau mobile avancé', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (261, 'ASR-M2-261', 'Cybersécurité avancée', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (262, 'ASR-M2-262', 'Développement d''application mobile', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (263, 'ASR-M2-263', 'Conception des logiciels', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (264, 'ASR-M2-264', 'Système d''Information Décisionnelle', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (265, 'ASR-M2-265', 'Projet python et programmation Orienté Objet', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (266, 'ASR-M2-266', 'Projet Machine Learning et Deep Learning', 3, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (267, 'ASR-M2-267', 'Modélisation mathématique', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (268, 'ASR-M2-268', 'Système multi-agents', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (269, 'ASR-M2-269', 'Aide à la décision et optimisation multi-critère', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (270, 'ASR-M2-270', 'Méthodologie d''élaboration de mémoires', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (271, 'ASR-M2-271', 'Méthodologie de recherche', 4, 13);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (272, 'GID-M1-272', 'Algèbre linéaire', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (273, 'GID-M1-273', 'Analyse', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (274, 'GID-M1-274', 'ProbaStat', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (275, 'GID-M1-275', 'Initiation à l''IA', 3, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (276, 'GID-M1-276', 'Initiation à la gouvernance de données', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (277, 'GID-M1-277', 'Base de données SQL et NoSQL', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (278, 'GID-M1-278', 'Développement backend', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (279, 'GID-M1-279', 'Développement frontend', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (280, 'GID-M1-280', 'R pour la Science de données', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (281, 'GID-M1-281', 'Français', 1.5, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (282, 'GID-M1-282', 'Anglais', 1.5, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (283, 'GID-M1-283', 'Stratégie et marketing digital', 1.5, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (284, 'GID-M1-284', 'Méthodologie de recherche', 1.5, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (285, 'GID-M1-285', 'Initiation à la cybersécurité', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (286, 'GID-M1-286', 'IAM et fournisseur d''identité', 3, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (287, 'GID-M1-287', 'Initiation à la science de données', 3, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (288, 'GID-M1-288', 'Initiation au Big Data', 3, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (289, 'GID-M1-289', 'Python pour la Science de données', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (290, 'GID-M1-290', 'Internet des objets IoT', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (291, 'GID-M1-291', 'Technologies mobiles et PWA', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (292, 'GID-M1-292', 'Architecture logicielle', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (293, 'GID-M1-293', 'Agile', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (294, 'GID-M1-294', 'Lean start-up', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (295, 'GID-M1-295', 'UX/UI Design', 2, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (296, 'GID-M1-296', 'Projet', 10, 14);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (297, 'GID-M2-297', 'Outils mathématiques pour l''IA', 3, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (298, 'GID-M2-298', 'Machine Learning & Deep Learning', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (299, 'GID-M2-299', 'Modélisation de connaissance', 1, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (300, 'GID-M2-300', 'Gouvernance de données', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (301, 'GID-M2-301', 'Big data', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (302, 'GID-M2-302', 'Structure de gouvernance de données', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (303, 'GID-M2-303', 'Interopérabilité et exploitation de données', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (304, 'GID-M2-304', 'Elaboration de dossier d''architecture technique', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (305, 'GID-M2-305', 'Interopérabilité de modèle', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (306, 'GID-M2-306', 'Prototypage et test utilisateur', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (307, 'GID-M2-307', 'Intégration et déploiement continus', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (308, 'GID-M2-308', 'Outils collaboratifs', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (309, 'GID-M2-309', 'Sécurité web', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (310, 'GID-M2-310', 'Qualimétrie', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (311, 'GID-M2-311', 'Gestion d''identité', 2, 15);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (312, 'OCC-M1-312', 'Concepts et fondements sur Internet des objets', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (313, 'OCC-M1-313', 'Conception de systèmes IoT évolutifs et distribués', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (314, 'OCC-M1-314', 'Modèles et architecture IoT', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (315, 'OCC-M1-315', 'Concepts et fondements sur la Cybersécurité', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (316, 'OCC-M1-316', 'Principes de base de la cryptographie', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (317, 'OCC-M1-317', 'Architecture de réseau IoT et topologies', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (318, 'OCC-M1-318', 'Protocoles et sécurité pour l''IoT', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (319, 'OCC-M1-319', 'Protocole de communication sécurisée pour les systèmes embarqués', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (320, 'OCC-M1-320', 'Circuits et matériels électroniques', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (321, 'OCC-M1-321', 'IoT sur microcontrôleur', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (322, 'OCC-M1-322', 'Capteurs connectés et équipement', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (323, 'OCC-M1-323', 'Commande et contrôle des actuateurs IoT', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (324, 'OCC-M1-324', 'Optimisation et Haute performance', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (325, 'OCC-M1-325', 'Complexité algorithmique et POO', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (326, 'OCC-M1-326', 'Plates-formes de développement IoT', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (327, 'OCC-M1-327', 'DevOps pour IoT', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (328, 'OCC-M1-328', 'Développement mobile', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (329, 'OCC-M1-329', 'Interaction homme-machine et IoT', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (330, 'OCC-M1-330', 'Programmation pour les systèmes embarqués', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (331, 'OCC-M1-331', 'Projet', 10, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (332, 'OCC-M1-332', 'Mathématique pour l''informatique', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (333, 'OCC-M1-333', 'Apprentissage automatique (ML & DL)', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (334, 'OCC-M1-334', 'Big Data et traitement des données IoT', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (335, 'OCC-M1-335', 'Sécurités des systèmes de contrôle industriel (ICS) et des SCADA', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (336, 'OCC-M1-336', 'Sécurité de communication mobile', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (337, 'OCC-M1-337', 'Sécurité des systèmes d''exploitation', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (338, 'OCC-M1-338', 'Sécurité de données et base de données en IoT', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (339, 'OCC-M1-339', 'Sécurité des applications web', 2, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (340, 'OCC-M1-340', 'Modèle de menace et attaques courantes', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (341, 'OCC-M1-341', 'Soft Skills', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (342, 'OCC-M1-342', 'Stratégie et Marketing digital', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (343, 'OCC-M1-343', 'Méthodologie de recherche', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (344, 'OCC-M1-344', 'Français', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (345, 'OCC-M1-345', 'Anglais', 1, 16);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (346, 'OCC-M2-346', 'Jumeaux numériques', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (347, 'OCC-M2-347', 'Réseaux mobiles et réseaux télécommunication', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (348, 'OCC-M2-348', 'Virtualisation et sécurité', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (349, 'OCC-M2-349', 'Communication de matériel IoT', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (350, 'OCC-M2-350', 'Norme et règlementation en cybersécurité', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (351, 'OCC-M2-351', 'Tests d''intrusion et évaluation de la sécurité', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (352, 'OCC-M2-352', 'Gestion de vulnérabilité, d''intrusion et correctif', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (353, 'OCC-M2-353', 'Menace et contre-mesures dans les réseaux sans fil', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (354, 'OCC-M2-354', 'Evaluation des risques en cybersécurité', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (355, 'OCC-M2-355', 'Conformité règlementaire et normes de sécurité', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (356, 'OCC-M2-356', 'Cloud computing', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (357, 'OCC-M2-357', 'Smart city', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (358, 'OCC-M2-358', 'Smart Data', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (359, 'OCC-M2-359', 'GeoIA', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (360, 'OCC-M2-360', 'Internet Industriel des objets et Internet of MedicalThings (IIoT et IoMT)', 2, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (361, 'OCC-M2-361', 'Modèles économiques de l''IoT', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (362, 'OCC-M2-362', 'Aspects juridiques et réglementaires de l''IoT', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (363, 'OCC-M2-363', 'Vulnérabilité et défenses dans les environnements industriels', 1, 17);
INSERT INTO subjects (id, code, name, credits, group_id) VALUES (364, 'OCC-M2-364', 'Applications et domaines d''utilisation de l''IoT', 1, 17);

-- ---------- TEACHER_SUBJECTS ----------
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (1, 24, 1);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (2, 20, 2);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (3, 19, 3);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (4, 11, 4);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (5, 16, 5);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (6, 5, 6);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (7, 16, 7);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (8, 5, 8);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (9, 26, 9);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (10, 15, 10);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (11, 12, 11);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (12, 36, 12);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (13, 11, 13);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (14, 23, 14);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (15, 31, 15);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (16, 31, 16);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (17, 36, 17);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (18, 19, 18);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (19, 13, 19);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (20, 2, 20);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (21, 7, 21);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (22, 20, 23);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (23, 24, 24);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (24, 14, 25);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (25, 23, 26);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (26, 16, 27);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (27, 16, 28);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (28, 25, 29);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (29, 19, 30);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (30, 26, 31);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (31, 23, 32);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (32, 25, 33);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (33, 23, 34);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (34, 36, 35);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (35, 30, 36);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (36, 12, 37);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (37, 12, 38);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (38, 5, 39);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (39, 31, 40);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (40, 31, 41);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (41, 36, 42);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (42, 2, 43);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (43, 10, 44);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (44, 26, 45);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (45, 19, 46);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (46, 12, 47);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (47, 26, 48);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (48, 23, 49);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (49, 28, 50);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (50, 5, 51);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (51, 8, 52);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (52, 21, 53);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (53, 28, 54);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (54, 30, 55);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (55, 5, 56);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (56, 30, 57);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (57, 36, 58);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (58, 31, 59);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (59, 36, 60);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (60, 30, 61);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (61, 12, 62);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (62, 12, 63);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (63, 2, 64);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (64, 10, 65);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (65, 9, 66);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (66, 34, 67);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (67, 18, 68);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (68, 21, 69);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (69, 22, 70);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (70, 11, 71);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (71, 19, 72);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (72, 21, 73);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (73, 16, 74);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (74, 26, 75);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (75, 25, 76);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (76, 26, 77);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (77, 26, 78);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (78, 8, 79);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (79, 28, 80);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (80, 3, 81);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (81, 27, 82);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (82, 12, 83);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (83, 5, 84);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (84, 23, 85);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (85, 5, 86);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (86, 11, 87);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (87, 12, 88);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (88, 30, 89);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (89, 10, 90);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (90, 2, 91);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (91, 19, 92);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (92, 19, 93);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (93, 26, 94);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (94, 26, 95);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (95, 16, 96);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (96, 3, 97);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (97, 16, 98);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (98, 11, 99);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (99, 5, 100);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (100, 5, 101);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (101, 36, 102);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (102, 12, 103);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (103, 30, 104);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (104, 30, 105);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (105, 30, 106);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (106, 21, 107);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (107, 21, 108);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (108, 12, 109);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (109, 26, 110);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (110, 8, 111);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (111, 3, 112);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (112, 24, 113);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (113, 20, 114);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (114, 19, 115);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (115, 11, 116);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (116, 16, 117);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (117, 16, 118);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (118, 26, 119);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (119, 19, 120);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (120, 25, 121);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (121, 25, 122);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (122, 25, 123);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (123, 25, 124);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (124, 19, 125);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (125, 19, 126);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (126, 21, 127);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (127, 26, 128);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (128, 4, 129);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (129, 34, 130);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (130, 29, 131);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (131, 2, 132);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (132, 29, 133);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (133, 25, 134);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (134, 19, 135);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (135, 19, 136);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (136, 26, 137);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (137, 5, 138);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (138, 28, 139);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (139, 19, 140);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (140, 28, 141);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (141, 28, 142);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (142, 26, 143);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (143, 26, 144);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (144, 15, 145);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (145, 3, 146);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (146, 2, 147);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (147, 10, 148);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (148, 9, 149);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (149, 34, 150);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (150, 18, 151);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (151, 21, 152);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (152, 22, 153);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (153, 11, 154);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (154, 19, 155);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (155, 21, 156);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (156, 11, 157);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (157, 16, 158);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (158, 26, 159);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (159, 25, 160);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (160, 26, 161);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (161, 26, 162);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (162, 2, 163);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (163, 28, 164);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (164, 3, 165);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (165, 8, 166);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (166, 19, 167);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (167, 19, 168);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (168, 10, 169);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (169, 2, 170);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (170, 13, 171);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (171, 8, 172);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (172, 8, 173);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (173, 27, 174);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (174, 26, 175);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (175, 28, 176);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (176, 8, 177);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (177, 19, 178);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (178, 8, 179);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (179, 19, 180);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (180, 16, 181);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (181, 16, 182);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (182, 11, 183);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (183, 14, 184);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (184, 21, 185);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (185, 8, 186);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (186, 3, 187);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (187, 24, 188);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (188, 20, 189);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (189, 19, 190);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (190, 11, 191);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (191, 16, 192);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (192, 16, 193);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (193, 12, 194);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (194, 31, 195);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (195, 5, 196);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (196, 15, 197);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (197, 23, 198);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (198, 15, 199);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (199, 12, 200);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (200, 30, 201);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (201, 12, 202);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (202, 31, 203);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (203, 36, 204);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (204, 36, 205);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (205, 30, 206);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (206, 12, 207);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (207, 30, 208);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (208, 36, 209);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (209, 12, 210);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (210, 2, 211);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (211, 10, 212);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (212, 29, 213);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (213, 5, 214);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (214, 12, 215);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (215, 23, 216);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (216, 31, 217);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (217, 5, 218);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (218, 12, 219);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (219, 15, 220);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (220, 23, 221);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (221, 12, 222);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (222, 12, 223);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (223, 15, 224);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (224, 30, 225);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (225, 12, 226);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (226, 23, 227);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (227, 30, 228);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (228, 36, 229);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (229, 36, 230);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (230, 30, 231);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (231, 30, 232);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (232, 30, 233);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (233, 2, 234);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (234, 10, 235);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (235, 18, 236);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (236, 21, 237);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (237, 22, 238);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (238, 11, 239);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (239, 19, 240);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (240, 21, 241);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (241, 11, 242);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (242, 16, 243);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (243, 26, 244);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (244, 36, 245);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (245, 12, 246);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (246, 12, 247);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (247, 12, 248);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (248, 23, 249);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (249, 30, 250);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (250, 12, 251);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (251, 5, 252);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (252, 30, 253);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (253, 10, 254);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (254, 2, 255);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (255, 36, 256);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (256, 5, 257);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (257, 5, 258);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (258, 30, 259);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (259, 30, 260);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (260, 12, 261);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (261, 26, 262);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (262, 15, 263);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (263, 16, 264);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (264, 12, 265);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (265, 12, 266);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (266, 14, 267);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (267, 21, 268);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (268, 11, 269);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (269, 8, 270);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (270, 3, 271);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (271, 33, 272);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (272, 33, 273);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (273, 19, 274);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (274, 27, 275);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (275, 28, 276);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (276, 25, 277);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (277, 25, 278);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (278, 25, 279);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (279, 14, 280);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (280, 1, 281);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (281, 2, 282);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (282, 27, 283);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (283, 3, 284);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (284, 15, 285);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (285, 3, 286);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (286, 27, 287);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (287, 3, 288);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (288, 27, 289);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (289, 8, 290);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (290, 8, 291);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (291, 37, 292);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (292, 35, 293);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (293, 28, 294);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (294, 3, 295);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (295, 8, 296);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (296, 33, 297);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (297, 27, 298);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (298, 3, 299);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (299, 28, 300);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (300, 3, 301);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (301, 28, 302);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (302, 3, 303);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (303, 27, 304);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (304, 3, 305);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (305, 28, 306);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (306, 28, 307);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (307, 35, 308);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (308, 11, 309);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (309, 3, 310);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (310, 3, 311);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (311, 8, 312);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (312, 8, 313);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (313, 37, 314);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (314, 15, 315);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (315, 3, 316);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (316, 12, 317);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (317, 12, 318);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (318, 12, 319);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (319, 31, 320);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (320, 31, 321);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (321, 8, 322);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (322, 8, 323);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (323, 11, 324);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (324, 16, 325);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (325, 28, 326);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (326, 28, 327);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (327, 8, 328);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (328, 3, 329);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (329, 8, 330);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (330, 8, 331);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (331, 33, 332);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (332, 27, 333);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (333, 3, 334);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (334, 8, 335);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (335, 8, 336);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (336, 12, 337);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (337, 8, 338);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (338, 11, 339);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (339, 12, 340);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (340, 35, 341);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (341, 27, 342);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (342, 3, 343);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (343, 1, 344);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (344, 2, 345);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (345, 28, 346);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (346, 12, 347);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (347, 11, 348);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (348, 37, 349);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (349, 15, 350);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (350, 15, 351);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (351, 15, 352);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (352, 15, 353);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (353, 15, 354);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (354, 8, 355);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (355, 11, 356);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (356, 17, 357);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (357, 32, 358);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (358, 6, 359);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (359, 28, 360);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (360, 8, 361);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (361, 28, 362);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (362, 8, 363);
INSERT INTO teacher_subjects (id, teacher_id, subject_id) VALUES (363, 8, 364);

-- ---------- RESET DES SEQUENCES (PostgreSQL) ----------
SELECT setval(pg_get_serial_sequence('groups', 'id'), (SELECT MAX(id) FROM groups));
SELECT setval(pg_get_serial_sequence('teachers', 'id'), (SELECT MAX(id) FROM teachers));
SELECT setval(pg_get_serial_sequence('subjects', 'id'), (SELECT MAX(id) FROM subjects));
SELECT setval(pg_get_serial_sequence('teacher_subjects', 'id'), (SELECT MAX(id) FROM teacher_subjects));